// Auto-generated by scripts/coverage.js. Do NOT edit — run 'npm run revise'.
const COVERAGE_DATA = {
  "generated": "2026-09-24T04:22:28.912Z",
  "inProgress": {
    "chapters": 1,
    "questions": 0,
    "topics": 7
  },
  "rules": {
    "total": 247,
    "withoutExample": 125
  },
  "notesGaps": [
    {
      "chapter": "Chapter 1: Java Introduction",
      "topic": "Hello World",
      "file": "src/Chapter_1_Java_Introduction/HelloWorld.java",
      "rule": "Note :- the text inside the quotes is a String literal, and `println` accepts any value, not only text."
    },
    {
      "chapter": "Chapter 2: Primitive Types",
      "topic": "String Example",
      "file": "src/Chapter_2_PrimitiveTypes/Strings/StringExample.java",
      "rule": "Contrast: a 'char' can hold only ONE character. A String can hold many. char uses single quotes ('A'), String uses double quotes (\"Hello\")."
    },
    {
      "chapter": "Chapter 2: Primitive Types",
      "topic": "String Example",
      "file": "src/Chapter_2_PrimitiveTypes/Strings/StringExample.java",
      "rule": "String immutability: once a String object is created, its value CANNOT be changed."
    },
    {
      "chapter": "Chapter 2: Primitive Types",
      "topic": "Key Words And Expressions In Java",
      "file": "src/Chapter_2_PrimitiveTypes/Sub_Chapter_2_KeyWords_And_Expressions/KeyWordsAndExpressionsInJava.java",
      "rule": "Keywords are reserved words in Java that have predefined meanings. They cannot be used as variable names, class names, or any other identifier."
    },
    {
      "chapter": "Chapter 2: Primitive Types",
      "topic": "Key Words And Expressions In Java",
      "file": "src/Chapter_2_PrimitiveTypes/Sub_Chapter_2_KeyWords_And_Expressions/KeyWordsAndExpressionsInJava.java",
      "rule": "Control flow keywords like 'if', 'for', 'while' and their surrounding parentheses are NOT part of the expression — only the content inside the parentheses forms the expression."
    },
    {
      "chapter": "Chapter 4: Statements And Indentations",
      "topic": "Unit Converter Deep Problem",
      "file": "src/Chapter_4_Statements_And_Indentations/Sub_Chapter_3_DeepProblems/UnitConverterDeepProblem.java",
      "rule": "Deep Problem: Multi-Domain Unit Converter — Implement a conversion utility that handles distance, weight, temperature, and volume. Each conversion must be isolated in its own method, and the program should generate readable tables for values 1 through 10 to simulate the kind of output a small engineering tool might need."
    },
    {
      "chapter": "Chapter 5: If Else Statements",
      "topic": "Code Blocks If Then Else",
      "file": "src/Chapter_5_If_Else_Statements/Sub_Chapter_2_Code_Block_If_Then_Else_Challenge/CodeBlocksIfThenElse.java",
      "rule": "An if-else if-else chain allows you to test multiple conditions in sequence, executing only the FIRST matching branch."
    },
    {
      "chapter": "Chapter 5: If Else Statements",
      "topic": "Code Blocks If Then Else",
      "file": "src/Chapter_5_If_Else_Statements/Sub_Chapter_2_Code_Block_If_Then_Else_Challenge/CodeBlocksIfThenElse.java",
      "rule": "The 'else' block is the fallback — it runs only when ALL preceding conditions are false."
    },
    {
      "chapter": "Chapter 5: If Else Statements",
      "topic": "Code Blocks If Then Else",
      "file": "src/Chapter_5_If_Else_Statements/Sub_Chapter_2_Code_Block_If_Then_Else_Challenge/CodeBlocksIfThenElse.java",
      "rule": "Scope example: if(gameOver) { int finalScore = ...; } — finalScore is only accessible inside the if block."
    },
    {
      "chapter": "Chapter 5: If Else Statements",
      "topic": "Code Blocks If Then Else",
      "file": "src/Chapter_5_If_Else_Statements/Sub_Chapter_2_Code_Block_If_Then_Else_Challenge/CodeBlocksIfThenElse.java",
      "rule": "Trying to use finalScore outside that if block would cause a compile error: \"Cannot resolve symbol 'finalScore'\"."
    },
    {
      "chapter": "Chapter 6: Methods In Java",
      "topic": "Barking Dog Coding Challenge",
      "file": "src/Chapter_6_Methods_In_Java/Sub_Chapter_2_Methods_Coding_Challenge/BarkingDogCodingChallenge.java",
      "rule": "shouldWakeUp(boolean barking, int hourOfDay) returns true only when barking is true and the time is before 8 or after 22."
    },
    {
      "chapter": "Chapter 6: Methods In Java",
      "topic": "Barking Dog Coding Challenge",
      "file": "src/Chapter_6_Methods_In_Java/Sub_Chapter_2_Methods_Coding_Challenge/BarkingDogCodingChallenge.java",
      "rule": "Important: combine conditions carefully so invalid hours never accidentally produce a true result."
    },
    {
      "chapter": "Chapter 6: Methods In Java",
      "topic": "Decimal Comparator Coding Challenge",
      "file": "src/Chapter_6_Methods_In_Java/Sub_Chapter_2_Methods_Coding_Challenge/DecimalComparatorCodingChallenge.java",
      "rule": "This challenge compares two double values only up to three decimal places."
    },
    {
      "chapter": "Chapter 6: Methods In Java",
      "topic": "Equality Printer Coding Challenge",
      "file": "src/Chapter_6_Methods_In_Java/Sub_Chapter_2_Methods_Coding_Challenge/EqualityPrinterCodingChallenge.java",
      "rule": "Any negative input is invalid and must print \"Invalid Value\" before any equality checks."
    },
    {
      "chapter": "Chapter 6: Methods In Java",
      "topic": "Leap Year Calculator Coding Challenge",
      "file": "src/Chapter_6_Methods_In_Java/Sub_Chapter_2_Methods_Coding_Challenge/LeapYearCalculatorCodingChallenge.java",
      "rule": "A valid year is a leap year when it is divisible by 4, except century years must also be divisible by 400."
    },
    {
      "chapter": "Chapter 6: Methods In Java",
      "topic": "Leap Year Calculator Coding Challenge",
      "file": "src/Chapter_6_Methods_In_Java/Sub_Chapter_2_Methods_Coding_Challenge/LeapYearCalculatorCodingChallenge.java",
      "rule": "Important: place the range validation first so invalid years cannot pass the divisibility checks."
    },
    {
      "chapter": "Chapter 6: Methods In Java",
      "topic": "Minutes To Years And Days Calculator Coding Challenge",
      "file": "src/Chapter_6_Methods_In_Java/Sub_Chapter_2_Methods_Coding_Challenge/MinutesToYearsAndDaysCalculatorCodingChallenge.java",
      "rule": "Negative minutes are invalid and must print exactly \"Invalid Value\"."
    },
    {
      "chapter": "Chapter 6: Methods In Java",
      "topic": "Positive Negative Zero Coding Challenge",
      "file": "src/Chapter_6_Methods_In_Java/Sub_Chapter_2_Methods_Coding_Challenge/PositiveNegativeZeroCodingChallenge.java",
      "rule": "Important: the zero case must be handled separately because zero is neither positive nor negative."
    },
    {
      "chapter": "Chapter 6: Methods In Java",
      "topic": "Speed Converter Coding Challenge",
      "file": "src/Chapter_6_Methods_In_Java/Sub_Chapter_2_Methods_Coding_Challenge/SpeedConverterCodingChallenge.java",
      "rule": "Math.round(double value) returns the nearest long, which is useful when a decimal conversion must be displayed as a whole number."
    },
    {
      "chapter": "Chapter 8: Java Looping Concepts",
      "topic": "For Loop Prime Number Challenge",
      "file": "src/Chapter_8_Java_Looping_Concepts/Sub_Chapter_2_For_Loop_Coding_Challenge/ForLoopPrimeNumberChallenge.java",
      "rule": "A prime number is only divisible by 1 and itself. The isPrime method checks divisibility up to number/2 (any factor beyond that would have a corresponding factor below it)."
    },
    {
      "chapter": "Chapter 8: Java Looping Concepts",
      "topic": "For Loop Sum3and5 Challenge",
      "file": "src/Chapter_8_Java_Looping_Concepts/Sub_Chapter_2_For_Loop_Coding_Challenge/ForLoopSum3and5Challenge.java",
      "rule": "Combined condition: (i % 3 == 0) && (i % 5 == 0) means the number must be divisible by BOTH 3 and 5 (i.e., divisible by 15)."
    },
    {
      "chapter": "Chapter 9: While And Do While Looping Concepts",
      "topic": "Digit Sum Coding Challenge",
      "file": "src/Chapter_9_WhileAndDoWhileLoopingConcepts/Sub_Chapter_3_While_Do_While_Loop_CodingChallenge/DigitSumCodingChallenge.java",
      "rule": "The method should only take a number that is a positive number."
    },
    {
      "chapter": "Chapter 9: While And Do While Looping Concepts",
      "topic": "First And Last Digit Sum Coding Challenge",
      "file": "src/Chapter_9_WhileAndDoWhileLoopingConcepts/Sub_Chapter_3_While_Do_While_Loop_CodingChallenge/FirstAndLastDigitSumCodingChallenge.java",
      "rule": "sumFirstAndLastDigit(0); → should return 0, the first digit and the last digit is 0 since we only have 1 digit, which gives us 0+0 and the sum is 0."
    },
    {
      "chapter": "Chapter 9: While And Do While Looping Concepts",
      "topic": "First And Last Digit Sum Coding Challenge",
      "file": "src/Chapter_9_WhileAndDoWhileLoopingConcepts/Sub_Chapter_3_While_Do_While_Loop_CodingChallenge/FirstAndLastDigitSumCodingChallenge.java",
      "rule": "sumFirstAndLastDigit(5); → should return 10, the first digit and the last digit is 5 since we only have 1 digit, which gives us 5+5 and the sum is 10."
    },
    {
      "chapter": "Chapter 9: While And Do While Looping Concepts",
      "topic": "Floor Pack Problem Coding Challenge",
      "file": "src/Chapter_9_WhileAndDoWhileLoopingConcepts/Sub_Chapter_3_While_Do_While_Loop_CodingChallenge/FloorPackProblemCodingChallenge.java",
      "rule": "Therefore, the sum of the kilos of bigCount and smallCount must be at least equal to the value of goal. The method should return true if it is possible to make a package with goal kilos of flour."
    },
    {
      "chapter": "Chapter 9: While And Do While Looping Concepts",
      "topic": "Floor Pack Problem Coding Challenge",
      "file": "src/Chapter_9_WhileAndDoWhileLoopingConcepts/Sub_Chapter_3_While_Do_While_Loop_CodingChallenge/FloorPackProblemCodingChallenge.java",
      "rule": "If the sum is greater than goal, ensure that only full bags are used towards the goal amount. For example, if goal = 9, bigCount = 2, and smallCount = 0, the method should return false since each big bag is 5 kilos and cannot be divided. However, if goal = 9, bigCount = 1, and smallCount = 5, the method should return true because of 1 full bigCount bag and 4 full smallCount bags equal goal, and it's okay if there are additional bags left over."
    },
    {
      "chapter": "Chapter 9: While And Do While Looping Concepts",
      "topic": "Greatest Common Divisor Coding Challenge",
      "file": "src/Chapter_9_WhileAndDoWhileLoopingConcepts/Sub_Chapter_3_While_Do_While_Loop_CodingChallenge/GreatestCommonDivisorCodingChallenge.java",
      "rule": "Both numbers must be >= 10; otherwise -1 is returned to indicate invalid input."
    },
    {
      "chapter": "Chapter 9: While And Do While Looping Concepts",
      "topic": "While Loop Coding Challenge",
      "file": "src/Chapter_9_WhileAndDoWhileLoopingConcepts/Sub_Chapter_3_While_Do_While_Loop_CodingChallenge/WhileLoopCodingChallenge.java",
      "rule": "Create a method called isEvenNumber that takes a parameter of type int. Its purpose is to determine if the argument passed to the method is an even number or not. Return true from the method if it's an even number; otherwise, return false. Next, use a while loop to test a range of numbers from 5 up to and including 20, but printing out only the even numbers determined by the call to the isEvenNumber method. Okay, so the challenge is to create a method called isEvenNumber, and it takes a parameter of type int."
    },
    {
      "chapter": "Chapter 11: Parsing Values Reading Input",
      "topic": "Parsing Values Reading Input",
      "file": "src/Chapter_11_Parsing_Values_Reading_Input/Sub_Chapter_1_Parsing_Values_And_Reading_input/ParsingValuesReadingInput.java",
      "rule": "You cannot do arithmetic on Strings — \"100\" - \"50\" is a compile error because - is not defined for Strings."
    },
    {
      "chapter": "Chapter 11: Parsing Values Reading Input",
      "topic": "Parsing Values Reading Input",
      "file": "src/Chapter_11_Parsing_Values_Reading_Input/Sub_Chapter_1_Parsing_Values_And_Reading_input/ParsingValuesReadingInput.java",
      "rule": "You also cannot use + for addition on Strings — \"100\" + \"50\" = \"10050\" (concatenation, not addition)."
    },
    {
      "chapter": "Chapter 11: Parsing Values Reading Input",
      "topic": "Parsing Values Reading Input",
      "file": "src/Chapter_11_Parsing_Values_Reading_Input/Sub_Chapter_1_Parsing_Values_And_Reading_input/ParsingValuesReadingInput.java",
      "rule": "If the String cannot be parsed (e.g., \"abc\"), a NumberFormatException is thrown at runtime."
    },
    {
      "chapter": "Chapter 11: Parsing Values Reading Input",
      "topic": "Paint Job Challenge",
      "file": "src/Chapter_11_Parsing_Values_Reading_Input/Sub_Chapter_2_Parsing_Values_Coding_Challenge/PaintJobChallenge.java",
      "rule": "Math.ceil() is used to round up — you always need whole buckets, never a fraction."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Classes And Inheritance",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_1_Classes_And_Inheritance/ClassesAndInheritance.java",
      "rule": "If a field is static, there is only one copy in memory, and this value is associated with the class or template itself."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Classes And Inheritance",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_1_Classes_And_Inheritance/ClassesAndInheritance.java",
      "rule": "A static method can't be dependent on any one object's state, so it can't reference any instance members."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Classes And Inheritance",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_1_Classes_And_Inheritance/ClassesAndInheritance.java",
      "rule": "A top-level class has only two valid access modifier options: public or none."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Classes And Inheritance",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_1_Classes_And_Inheritance/ClassesAndInheritance.java",
      "rule": "Description :- When the modifier is omitted, this has special meaning, called package access, meaning the member is accessible only to classes in the same package"
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Car",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_2_Getters_Encapsulation_Object_Access/Car.java",
      "rule": "When writing methods that use non-static fields, your method can't be declared static."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Car",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_2_Getters_Encapsulation_Object_Access/Car.java",
      "rule": "Encapsulation is one of the four pillars of OOP. It means hiding the internal state of an object and only allowing access through controlled methods (getters and setters)."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Car",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_2_Getters_Encapsulation_Object_Access/Car.java",
      "rule": "All instance fields in this class are declared 'private' — they cannot be accessed directly from outside the class."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Car",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_2_Getters_Encapsulation_Object_Access/Car.java",
      "rule": "Setters can VALIDATE data before assigning it. Example: setMake() only accepts \"holden\", \"porsche\", or \"tesla\" — anything else becomes \"Unsupported\"."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Car",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_2_Getters_Encapsulation_Object_Access/Car.java",
      "rule": "This is the power of encapsulation — the Car class enforces its own rules about valid data. Outside code cannot bypass these rules."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Main",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_2_Getters_Encapsulation_Object_Access/Main.java",
      "rule": "Private fields CANNOT be accessed directly from outside the class (e.g., car.make = \"Porsche\" would be a compile error)."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Main",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_2_Getters_Encapsulation_Object_Access/Main.java",
      "rule": "The setMake() method in Car validates the input — only \"holden\", \"porsche\", or \"tesla\" are accepted. Passing \"Maserati\" results in \"Unsupported\"."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Main",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_2_Getters_Encapsulation_Object_Access/Main.java",
      "rule": "This demonstrates encapsulation at work — the class controls what data is valid, and outside code cannot bypass those rules."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Method Overloading Second And Minutes Challenge",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_3_Classes_Challenge/MethodOverloadingSecondAndMinutesChallenge.java",
      "rule": "Create a 2nd method of the same name but with only one parameter seconds."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Constructor Concept",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_4_Constructors/Sub_Chapter_1_ConstructorConcept/ConstructorConcept.java",
      "rule": "It should never include a return type from a constructor, not even void."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Constructor Concept",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_4_Constructors/Sub_Chapter_1_ConstructorConcept/ConstructorConcept.java",
      "rule": "Implicitly called in Java means we can't see the code in the source, but it's in the byte code, generated during the compilation process."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Constructor Concept",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_4_Constructors/Sub_Chapter_1_ConstructorConcept/ConstructorConcept.java",
      "rule": "It's only ever called once, at the start, when the object is created."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Constructor Concept",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_4_Constructors/Sub_Chapter_1_ConstructorConcept/ConstructorConcept.java",
      "rule": "If the number of parameters is the same between two constructors, their types, or order of the types must differ."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Constructor Concept",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_4_Constructors/Sub_Chapter_1_ConstructorConcept/ConstructorConcept.java",
      "rule": "The special statement this() is used to execute another constructor, passing it arguments if required. And this() must be the first executable statement if it's used from another constructor."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Constructor Concept",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_4_Constructors/Sub_Chapter_1_ConstructorConcept/ConstructorConcept.java",
      "rule": "The type and number of arguments passed inside the this() keyword must match one of the defined constructors."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Constructor Concept",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_4_Constructors/Sub_Chapter_1_ConstructorConcept/ConstructorConcept.java",
      "rule": "If you define ANY constructor explicitly, Java does NOT provide the default constructor — you must define it yourself if needed."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Constructor Concept",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_4_Constructors/Sub_Chapter_1_ConstructorConcept/ConstructorConcept.java",
      "rule": "Constructor chaining: one constructor calls another using 'this(args...)'. The this() call MUST be the FIRST statement in the constructor."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Constructor Concept",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_4_Constructors/Sub_Chapter_1_ConstructorConcept/ConstructorConcept.java",
      "rule": "A class can have both 'this()' chaining (calls another constructor in same class) and 'super()' chaining (calls parent constructor), but never BOTH in the same constructor."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "This And Super",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_4_Constructors/Sub_Chapter_2_This_And_Super/ThisAndSuper.java",
      "rule": "2) this keyword is required when we have a parameter with the same name as an instance variable or field."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "This And Super",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_4_Constructors/Sub_Chapter_2_This_And_Super/ThisAndSuper.java",
      "rule": "2) The call to this() parentheses can only be used in a constructor, and it must be the first statement in a constructor."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "This And Super",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_4_Constructors/Sub_Chapter_2_This_And_Super/ThisAndSuper.java",
      "rule": "1) The only way to call a parent constructor is by calling super() parentheses, which calls the parent constructor."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "This And Super",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_4_Constructors/Sub_Chapter_2_This_And_Super/ThisAndSuper.java",
      "rule": "2) The Java compiler puts a default call to super() parentheses if we don't add it, and it's always a call to the no argument constructor, which is inserted by the compiler."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "This And Super",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_4_Constructors/Sub_Chapter_2_This_And_Super/ThisAndSuper.java",
      "rule": "3) The call to super() parentheses must be the first statement in each constructor."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "This And Super",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_4_Constructors/Sub_Chapter_2_This_And_Super/ThisAndSuper.java",
      "rule": "2) A constructor can have a call to super() or this(), but never both"
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "This And Super",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_4_Constructors/Sub_Chapter_2_This_And_Super/ThisAndSuper.java",
      "rule": "'this()' — calls another constructor in the SAME class. Must be the FIRST statement in the constructor. Used for constructor chaining."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "This And Super",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_4_Constructors/Sub_Chapter_2_This_And_Super/ThisAndSuper.java",
      "rule": "'super()' — calls the parent class constructor. Must be the FIRST statement in the constructor. Java inserts a no-arg super() call automatically if you don't write one."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "This And Super",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_4_Constructors/Sub_Chapter_2_This_And_Super/ThisAndSuper.java",
      "rule": "You can use EITHER this() OR super() in a constructor, but NEVER BOTH — each must be the first statement, and there can only be one first statement."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Good Constructor Super Call Example",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_4_Constructors/Sub_Chapter_3_Constructor_Good_Practices/Super_Call_Example/GoodConstructorSuperCallExample.java",
      "rule": "So, the child class cannot depend on the implicit super() call, and the child constructor has to call the parameterised constructor of the parent class using super(x, y), passing arguments that match it."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Good Constructor Super Call Example",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_4_Constructors/Sub_Chapter_3_Constructor_Good_Practices/Super_Call_Example/GoodConstructorSuperCallExample.java",
      "rule": "In this example, the parent class GoodConstructorSuperCallExample has only 1 parameterised constructor, which accepts x and y, so the free no - args constructor is not created for the parent class."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Good Constructor Super Call Example",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_4_Constructors/Sub_Chapter_3_Constructor_Good_Practices/Super_Call_Example/GoodConstructorSuperCallExample.java",
      "rule": "So the implicit super() call fails, because there is no constructor in the parent class which takes no arguments, and the compiler throws an error like this :-"
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Good Constructor Super Call Example",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_4_Constructors/Sub_Chapter_3_Constructor_Good_Practices/Super_Call_Example/GoodConstructorSuperCallExample.java",
      "rule": "constructor GoodConstructorSuperCallExample in class GoodConstructorSuperCallExample cannot be applied to given types; required: int,int; found: no arguments"
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Good Constructor Super Call Example",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_4_Constructors/Sub_Chapter_3_Constructor_Good_Practices/Super_Call_Example/GoodConstructorSuperCallExample.java",
      "rule": "If the fields of the parent class are private, as x and y are here, the child class cannot set them directly, and super(...) is the only way to initialize them."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Good Constructor Super Call Example",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_4_Constructors/Sub_Chapter_3_Constructor_Good_Practices/Super_Call_Example/GoodConstructorSuperCallExample.java",
      "rule": "Note :- this() and super() cannot be used together in the same constructor, because both of them have to be the first statement, and a constructor body can have only 1 first statement. So Java would have no way to decide which of the two constructors has to be called first."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Good Constructor Super Call Example",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_4_Constructors/Sub_Chapter_3_Constructor_Good_Practices/Super_Call_Example/GoodConstructorSuperCallExample.java",
      "rule": "If either call is written after another statement, the compiler throws an error like :-"
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Good Constructor Super Call Example",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_4_Constructors/Sub_Chapter_3_Constructor_Good_Practices/Super_Call_Example/GoodConstructorSuperCallExample.java",
      "rule": "call to this must be first statement in constructor call to super must be first statement in constructor"
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Good Constructor Super Call Example",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_4_Constructors/Sub_Chapter_3_Constructor_Good_Practices/Super_Call_Example/GoodConstructorSuperCallExample.java",
      "rule": "Note :- Why is this needed when 1 constructor is already calling the parent constructor ? Because creating an object runs only 1 constructor of the child class, the one which matches the arguments passed with new."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Good Constructor Super Call Example",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_4_Constructors/Sub_Chapter_3_Constructor_Good_Practices/Super_Call_Example/GoodConstructorSuperCallExample.java",
      "rule": "The other constructors do not run at all, so they cannot do the work on behalf of the constructor which is called. That is why each constructor has to reach a super() call on its own, either directly through super(args...), or through this(args...) chaining, and exactly 1 super() call happens for each object created."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Good Constructor Super Call Example",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_4_Constructors/Sub_Chapter_3_Constructor_Good_Practices/Super_Call_Example/GoodConstructorSuperCallExample.java",
      "rule": "Important :- the parent constructor is always called, either implicitly by the compiler or explicitly through super(), and the super() call has to be the first statement in the child constructor."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Good Constructor Super Call Example",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_4_Constructors/Sub_Chapter_3_Constructor_Good_Practices/Super_Call_Example/GoodConstructorSuperCallExample.java",
      "rule": "Pitfall :- if the parent class has no accessible no - args constructor, and a child constructor has no super() call, the compiler throws an error, for example \"constructor GoodConstructorSuperCallExample in class GoodConstructorSuperCallExample cannot be applied to given types\"."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Good Constructor Super Call Example",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_4_Constructors/Sub_Chapter_3_Constructor_Good_Practices/Super_Call_Example/GoodConstructorSuperCallExample.java",
      "rule": "Note :- a constructor can have a call to this() or super(), but never both, because both of these calls have to be the first statement, and only 1 statement can be first in a constructor body."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Good Constructor Super Call Example",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_4_Constructors/Sub_Chapter_3_Constructor_Good_Practices/Super_Call_Example/GoodConstructorSuperCallExample.java",
      "rule": "Note :- if the only constructor of the parent class is private, the child class cannot call it at all."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Good Constructor Super Call Example",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_4_Constructors/Sub_Chapter_3_Constructor_Good_Practices/Super_Call_Example/GoodConstructorSuperCallExample.java",
      "rule": "Java creates the free no - args constructor for a class only when that class declares no constructor at all."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Bad Constructor This Call Example",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_4_Constructors/Sub_Chapter_3_Constructor_Good_Practices/This_Call_Example/BadConstructorThisCallExample.java",
      "rule": "If you ever need to change the default value or add validation, you must update EVERY constructor separately — error-prone."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Good Constructor This Call Example",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_4_Constructors/Sub_Chapter_3_Constructor_Good_Practices/This_Call_Example/GoodConstructorThisCallExample.java",
      "rule": "The variables will always be initialized in the 3rd constructor, and only there."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Good Constructor This Call Example",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_4_Constructors/Sub_Chapter_3_Constructor_Good_Practices/This_Call_Example/GoodConstructorThisCallExample.java",
      "rule": "Only ONE place in the code initialises the fields — changes are made once, not everywhere."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Customer",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_5_Constructors_Challenge/Customer.java",
      "rule": "Create the getter methods only for each field. You don't need to create the setters."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Static And Instance Methods",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_7_Static_And_Instance_Methods/StaticAndInstanceMethods.java",
      "rule": "Static methods CANNOT access instance fields or call instance methods directly (no 'this' in static context)."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Static And Instance Methods",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_7_Static_And_Instance_Methods/StaticAndInstanceMethods.java",
      "rule": "The main() method is static — it runs without any object being created. That's why you can't use 'this' in main."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Student Record",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_9_JavaRecords/StudentRecord.java",
      "rule": "5) It contains only the most fundamental methods, such as constructors and accessors (or getters)."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Student Record",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_9_JavaRecords/StudentRecord.java",
      "rule": "iv) Simply put, it means the field can't be modified."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Student Record",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_9_JavaRecords/StudentRecord.java",
      "rule": "ALL fields in a record are automatically: private and final (cannot be changed after construction)."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Student Record",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_9_JavaRecords/StudentRecord.java",
      "rule": "Java auto-generates for every record: a canonical constructor, accessor methods (field name only, no 'get' prefix), equals(), hashCode(), and toString()."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Student Record",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_9_JavaRecords/StudentRecord.java",
      "rule": "Records have NO setter methods — they are immutable by design. You cannot change a record's data after creation."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Animal",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_11_Inheritance/AnimalInheritanceExample/Animal.java",
      "rule": "The method signature (name + parameter types) must match exactly for overriding to work."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Inheritance",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_11_Inheritance/AnimalInheritanceExample/Inheritance.java",
      "rule": "In Java, a class can only extend ONE direct parent (single inheritance), but inherits all the way up the hierarchy."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Main",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_11_Inheritance/AnimalInheritanceExample/ObjectClass/Main.java",
      "rule": "Java only supports 1 class in the extends class"
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Dog",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_13_Method_OverLoading_In_Java/MethodOverloadingExample/Dog.java",
      "rule": "careful: adding a different return type to bark(int number) would not create another overload; the parameter list must differ."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Covariant Return Type",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_14_Method_Overriding_In_Java/MethodOverridingExample/CovariantReturnType/CovariantReturnType.java",
      "rule": "important: constructors cannot be overridden because they are not inherited; only methods can be overridden."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Covariant Return Type",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_14_Method_Overriding_In_Java/MethodOverridingExample/CovariantReturnType/CovariantReturnType.java",
      "rule": "pitfall: a different return type can help overriding only when it is covariant; return type alone still does not create an overload."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Method Overriding In Java",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_14_Method_Overriding_In_Java/MethodOverridingInJava.java",
      "rule": "We can't override static methods,only instance methods can be overridden."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Method Overriding In Java",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_14_Method_Overriding_In_Java/MethodOverridingInJava.java",
      "rule": "1) Firstly, It must have the same name and same arguments."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Method Overriding In Java",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_14_Method_Overriding_In_Java/MethodOverridingInJava.java",
      "rule": "3) It can't have a lower access modifier. In other words, it can't have more restrictive access privileges. For example, if the parent's method is protected, then using private in the child's overridden method is not allowed. However, using public for the child's method would be allowed, in this example."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Method Overriding In Java",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_14_Method_Overriding_In_Java/MethodOverridingInJava.java",
      "rule": "4) Only inherited methods can be overridden, in other words, methods can be overridden only in child classes."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Method Overriding In Java",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_14_Method_Overriding_In_Java/MethodOverridingInJava.java",
      "rule": "5) Constructors and private methods cannot be overridden."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Method Overriding In Java",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_14_Method_Overriding_In_Java/MethodOverridingInJava.java",
      "rule": "6) And Methods that are final also cannot be overridden."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Method Over Loading Vs Method Overriding Difference",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_15_Method_Overloading_Vs_Method_Overriding/MethodOverLoadingVsMethodOverridingDifference.java",
      "rule": "important: return type, access modifier, and thrown exceptions do not by themselves create overloaded methods; the parameter list must differ."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Shape Hierarchy Deep Problem",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_16_DeepProblems/ShapeHierarchyDeepProblem.java",
      "rule": "Deep Problem: Shape Hierarchy and Polymorphic Reporting — Model a small geometry system with a base Shape type and specialized subclasses for circles, rectangles, and triangles. Each shape must compute its own area, while a shared reporting method uses instanceof checks and polymorphism to print detailed runtime information."
    },
    {
      "chapter": "Chapter 14: Strings",
      "topic": "String Method And Best Practices",
      "file": "src/Chapter_14_Strings/Sub_Chapter_2_String_Methods_And_Best_Practices/StringMethodAndBestPractices.java",
      "rule": "Note :- the original String is never changed, because String is immutable. Every method of the String class returns a new String instead of changing the existing one."
    },
    {
      "chapter": "Chapter 14: Strings",
      "topic": "String Method And Best Practices",
      "file": "src/Chapter_14_Strings/Sub_Chapter_2_String_Methods_And_Best_Practices/StringMethodAndBestPractices.java",
      "rule": "isEmpty() returns true only when the length is 0, so a String with only spaces, like \" \", returns false."
    },
    {
      "chapter": "Chapter 14: Strings",
      "topic": "String Method And Best Practices",
      "file": "src/Chapter_14_Strings/Sub_Chapter_2_String_Methods_And_Best_Practices/StringMethodAndBestPractices.java",
      "rule": "isBlank() returns true when the length is 0, or when the String has only whitespace characters."
    },
    {
      "chapter": "Chapter 14: Strings",
      "topic": "String Method And Best Practices",
      "file": "src/Chapter_14_Strings/Sub_Chapter_2_String_Methods_And_Best_Practices/StringMethodAndBestPractices.java",
      "rule": "Note :- for user input validation, always use isBlank(), otherwise the user can enter spaces and bypass it."
    },
    {
      "chapter": "Chapter 14: Strings",
      "topic": "String Method And Best Practices",
      "file": "src/Chapter_14_Strings/Sub_Chapter_2_String_Methods_And_Best_Practices/StringMethodAndBestPractices.java",
      "rule": "trim() removes only ASCII whitespace, which means characters with a codepoint of 32 or less."
    },
    {
      "chapter": "Chapter 14: Strings",
      "topic": "String Method And Best Practices",
      "file": "src/Chapter_14_Strings/Sub_Chapter_2_String_Methods_And_Best_Practices/StringMethodAndBestPractices.java",
      "rule": "equals() returns true only when the other object is also a String."
    },
    {
      "chapter": "Chapter 14: Strings",
      "topic": "String Method And Best Practices",
      "file": "src/Chapter_14_Strings/Sub_Chapter_2_String_Methods_And_Best_Practices/StringMethodAndBestPractices.java",
      "rule": "Note :- use replace() for literal replacements, and use replaceAll() or replaceFirst() only when pattern matching is really needed."
    },
    {
      "chapter": "Chapter 14: Strings",
      "topic": "String Method And Best Practices",
      "file": "src/Chapter_14_Strings/Sub_Chapter_2_String_Methods_And_Best_Practices/StringMethodAndBestPractices.java",
      "rule": "Pitfall :- in replaceAll(\".\", \"X\"), the \".\" is a Regular Expression which matches ANY character, so every character of the String gets replaced. To replace only the dots, use replaceAll(\"\\\\.\", \"X\") or use replace(\".\", \"X\")."
    },
    {
      "chapter": "Chapter 14: Strings",
      "topic": "String Method And Best Practices",
      "file": "src/Chapter_14_Strings/Sub_Chapter_2_String_Methods_And_Best_Practices/StringMethodAndBestPractices.java",
      "rule": "concat() joins 2 Strings, but it throws NullPointerException when the argument is null."
    },
    {
      "chapter": "Chapter 14: Strings",
      "topic": "String Method And Best Practices",
      "file": "src/Chapter_14_Strings/Sub_Chapter_2_String_Methods_And_Best_Practices/StringMethodAndBestPractices.java",
      "rule": "Pitfall :- never join Strings inside a loop using concat() or +, because a new String object gets created every time and the program becomes slow. Use StringBuilder inside the loop instead."
    },
    {
      "chapter": "Chapter 14: Strings",
      "topic": "String Method And Best Practices",
      "file": "src/Chapter_14_Strings/Sub_Chapter_2_String_Methods_And_Best_Practices/StringMethodAndBestPractices.java",
      "rule": "1) substring(length) is valid, it returns an empty String and does not throw an exception."
    },
    {
      "chapter": "Chapter 14: Strings",
      "topic": "String Method And Best Practices",
      "file": "src/Chapter_14_Strings/Sub_Chapter_2_String_Methods_And_Best_Practices/StringMethodAndBestPractices.java",
      "rule": "3) repeat(-1) throws IllegalArgumentException, because the count cannot be negative."
    },
    {
      "chapter": "Chapter 14: Strings",
      "topic": "String Method And Best Practices",
      "file": "src/Chapter_14_Strings/Sub_Chapter_2_String_Methods_And_Best_Practices/StringMethodAndBestPractices.java",
      "rule": "4) concat(null) throws NullPointerException, but \"hello\" + null gives \"hellonull\"."
    },
    {
      "chapter": "Chapter 14: Strings",
      "topic": "String Builder Concepts",
      "file": "src/Chapter_14_Strings/Sub_Chapter_3_StringBuilder/StringBuilderConcepts.java",
      "rule": "Note :- StringBuffer is the older type. Its methods are synchronised, which costs speed, so StringBuilder is preferred when only one thread is involved."
    },
    {
      "chapter": "Chapter 14: Strings",
      "topic": "String Vs String Buffer Vs String Builder",
      "file": "src/Chapter_14_Strings/Sub_Chapter_3_StringBuilder/StringVsStringBufferVsStringBuilder.java",
      "rule": "String is immutable. Once a String object has been created, its character contents cannot be changed. An operation such as concat() creates and returns a new String; it does not change the original String. If the result is not assigned to a variable, the original value remains unchanged."
    },
    {
      "chapter": "Chapter 14: Strings",
      "topic": "String Vs String Buffer Vs String Builder",
      "file": "src/Chapter_14_Strings/Sub_Chapter_3_StringBuilder/StringVsStringBufferVsStringBuilder.java",
      "rule": "StringBuffer is also mutable and exposes nearly the same API as StringBuilder. Its mutating methods are synchronized, so operations on one shared buffer are coordinated between threads. That synchronization adds overhead, so StringBuilder is normally faster when the buffer is confined to one thread. Choose StringBuffer only when its thread-safety behavior is actually required by the design."
    },
    {
      "chapter": "Chapter 14: Strings",
      "topic": "String Vs String Buffer Vs String Builder",
      "file": "src/Chapter_14_Strings/Sub_Chapter_3_StringBuilder/StringVsStringBufferVsStringBuilder.java",
      "rule": "- Use StringBuffer only when multiple threads must share and update the same text buffer, and external synchronization is not being used instead."
    },
    {
      "chapter": "Chapter 14: Strings",
      "topic": "String Vs String Buffer Vs String Builder",
      "file": "src/Chapter_14_Strings/Sub_Chapter_3_StringBuilder/StringVsStringBufferVsStringBuilder.java",
      "rule": "- Local variables live in that frame. A reference variable, such as a String or a StringBuilder variable, does NOT hold the object itself. It only holds a reference, which is like an address that points to the real object on the heap."
    },
    {
      "chapter": "Chapter 14: Strings",
      "topic": "String Vs String Buffer Vs String Builder",
      "file": "src/Chapter_14_Strings/Sub_Chapter_3_StringBuilder/StringVsStringBufferVsStringBuilder.java",
      "rule": "- It stores each unique String literal only once, so the same text is not duplicated in memory."
    },
    {
      "chapter": "Chapter 14: Strings",
      "topic": "String Vs String Buffer Vs String Builder",
      "file": "src/Chapter_14_Strings/Sub_Chapter_3_StringBuilder/StringVsStringBufferVsStringBuilder.java",
      "rule": "A reference variable always sits on the stack and points to an object on the heap. The real difference is whether changing the text edits that same object or quietly creates a new one."
    },
    {
      "chapter": "Chapter 14: Strings",
      "topic": "String Vs String Buffer Vs String Builder",
      "file": "src/Chapter_14_Strings/Sub_Chapter_3_StringBuilder/StringVsStringBufferVsStringBuilder.java",
      "rule": "String is IMMUTABLE. A method like concat never changes the original text. It returns a brand new String instead. If you ignore that returned value, your variable still points to the old, unchanged object. Only reassigning the variable makes it point to the new object, and even then the old object is left untouched."
    },
    {
      "chapter": "Chapter 14: Strings",
      "topic": "String Vs String Buffer Vs String Builder",
      "file": "src/Chapter_14_Strings/Sub_Chapter_3_StringBuilder/StringVsStringBufferVsStringBuilder.java",
      "rule": "StringBuilder and StringBuffer are MUTABLE. A method like append edits the same object in place and hands the same object back to you. The variable keeps pointing to that one object, but the object's contents have changed. No new object is created just to change the text, unless the buffer runs out of room and has to grow, which only swaps the internal array while keeping the same builder object. StringBuffer works the same way, except its methods are synchronized so several threads can share it safely."
    }
  ],
  "concepts": {
    "covered": 28,
    "studied": 29,
    "missing": [],
    "objectives": [
      {
        "name": "Working with Java Data Types",
        "ahead": false,
        "covered": 9,
        "total": 9
      },
      {
        "name": "Controlling Program Flow",
        "ahead": false,
        "covered": 5,
        "total": 5
      },
      {
        "name": "Java Object Oriented Approach",
        "ahead": false,
        "covered": 10,
        "total": 11
      },
      {
        "name": "Exception Handling",
        "ahead": false,
        "covered": 4,
        "total": 4
      },
      {
        "name": "Working with Arrays and Collections",
        "ahead": true,
        "covered": 1,
        "total": 3
      },
      {
        "name": "Working with Streams and Lambda Expressions",
        "ahead": true,
        "covered": 0,
        "total": 2
      },
      {
        "name": "Java Platform Module System",
        "ahead": true,
        "covered": 0,
        "total": 1
      },
      {
        "name": "Concurrency",
        "ahead": true,
        "covered": 0,
        "total": 1
      },
      {
        "name": "Java I/O API",
        "ahead": true,
        "covered": 0,
        "total": 1
      },
      {
        "name": "Secure Coding in Java SE Application",
        "ahead": true,
        "covered": 0,
        "total": 0
      },
      {
        "name": "Database Applications with JDBC",
        "ahead": true,
        "covered": 0,
        "total": 1
      },
      {
        "name": "Localization",
        "ahead": true,
        "covered": 0,
        "total": 1
      },
      {
        "name": "Annotations",
        "ahead": true,
        "covered": 0,
        "total": 1
      }
    ],
    "byConcept": {
      "overloading": 223,
      "inheritance": 207,
      "strings": 178,
      "string-pool": 177,
      "statements": 174,
      "casting": 170,
      "polymorphism": 170,
      "constructors": 159,
      "static": 152,
      "encapsulation": 142,
      "classes": 128,
      "operators": 118,
      "break-continue": 117,
      "object-class": 116,
      "abstract": 103,
      "records-enums": 103,
      "wrappers": 96,
      "loops": 74,
      "if-else": 60,
      "literals": 57,
      "switch": 43,
      "checked-unchecked": 27,
      "multi-catch": 27,
      "primitives": 22,
      "var": 22,
      "text-blocks": 21,
      "arrays": 21,
      "exceptions": 3,
      "throw-throws": 1
    }
  }
};
