// Auto-generated by scripts/coverage.js. Do NOT edit — run 'npm run revise'.
const COVERAGE_DATA = {
  "generated": "2026-09-24T07:45:36.726Z",
  "inProgress": {
    "chapters": 1,
    "questions": 0,
    "topics": 7
  },
  "rules": {
    "total": 215,
    "withoutExample": 16
  },
  "notesGaps": [
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Classes And Inheritance",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_1_Classes_And_Inheritance/ClassesAndInheritance.java",
      "rule": "If a field is static, there is only one copy in memory, and this value is associated with the class or template itself."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Classes And Inheritance",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_1_Classes_And_Inheritance/ClassesAndInheritance.java",
      "rule": "A static method can't be dependent on any one object's state, so it can't reference any instance members."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Classes And Inheritance",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_1_Classes_And_Inheritance/ClassesAndInheritance.java",
      "rule": "A top-level class has only two valid access modifier options: public or none."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Classes And Inheritance",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_1_Classes_And_Inheritance/ClassesAndInheritance.java",
      "rule": "Description :- When the modifier is omitted, this has special meaning, called package access, meaning the member is accessible only to classes in the same package"
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "This And Super",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_4_Constructors/Sub_Chapter_2_This_And_Super/ThisAndSuper.java",
      "rule": "2) this keyword is required when we have a parameter with the same name as an instance variable or field."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "This And Super",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_4_Constructors/Sub_Chapter_2_This_And_Super/ThisAndSuper.java",
      "rule": "2) The call to this() parentheses can only be used in a constructor, and it must be the first statement in a constructor."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "This And Super",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_4_Constructors/Sub_Chapter_2_This_And_Super/ThisAndSuper.java",
      "rule": "1) The only way to call a parent constructor is by calling super() parentheses, which calls the parent constructor."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "This And Super",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_4_Constructors/Sub_Chapter_2_This_And_Super/ThisAndSuper.java",
      "rule": "2) The Java compiler puts a default call to super() parentheses if we don't add it, and it's always a call to the no argument constructor, which is inserted by the compiler."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "This And Super",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_4_Constructors/Sub_Chapter_2_This_And_Super/ThisAndSuper.java",
      "rule": "3) The call to super() parentheses must be the first statement in each constructor."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "This And Super",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_4_Constructors/Sub_Chapter_2_This_And_Super/ThisAndSuper.java",
      "rule": "2) A constructor can have a call to super() or this(), but never both"
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Method Overriding In Java",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_14_Method_Overriding_In_Java/MethodOverridingInJava.java",
      "rule": "We can't override static methods,only instance methods can be overridden."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Method Overriding In Java",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_14_Method_Overriding_In_Java/MethodOverridingInJava.java",
      "rule": "1) Firstly, It must have the same name and same arguments."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Method Overriding In Java",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_14_Method_Overriding_In_Java/MethodOverridingInJava.java",
      "rule": "3) It can't have a lower access modifier. In other words, it can't have more restrictive access privileges. For example, if the parent's method is protected, then using private in the child's overridden method is not allowed. However, using public for the child's method would be allowed, in this example."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Method Overriding In Java",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_14_Method_Overriding_In_Java/MethodOverridingInJava.java",
      "rule": "4) Only inherited methods can be overridden, in other words, methods can be overridden only in child classes."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Method Overriding In Java",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_14_Method_Overriding_In_Java/MethodOverridingInJava.java",
      "rule": "5) Constructors and private methods cannot be overridden."
    },
    {
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Method Overriding In Java",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_14_Method_Overriding_In_Java/MethodOverridingInJava.java",
      "rule": "6) And Methods that are final also cannot be overridden."
    }
  ],
  "concepts": {
    "covered": 28,
    "studied": 29,
    "missing": [],
    "objectives": [
      {
        "name": "Working with Java Data Types",
        "ahead": false,
        "covered": 9,
        "total": 9
      },
      {
        "name": "Controlling Program Flow",
        "ahead": false,
        "covered": 5,
        "total": 5
      },
      {
        "name": "Java Object Oriented Approach",
        "ahead": false,
        "covered": 10,
        "total": 11
      },
      {
        "name": "Exception Handling",
        "ahead": false,
        "covered": 4,
        "total": 4
      },
      {
        "name": "Working with Arrays and Collections",
        "ahead": true,
        "covered": 1,
        "total": 3
      },
      {
        "name": "Working with Streams and Lambda Expressions",
        "ahead": true,
        "covered": 0,
        "total": 2
      },
      {
        "name": "Java Platform Module System",
        "ahead": true,
        "covered": 0,
        "total": 1
      },
      {
        "name": "Concurrency",
        "ahead": true,
        "covered": 0,
        "total": 1
      },
      {
        "name": "Java I/O API",
        "ahead": true,
        "covered": 0,
        "total": 1
      },
      {
        "name": "Secure Coding in Java SE Application",
        "ahead": true,
        "covered": 0,
        "total": 0
      },
      {
        "name": "Database Applications with JDBC",
        "ahead": true,
        "covered": 0,
        "total": 1
      },
      {
        "name": "Localization",
        "ahead": true,
        "covered": 0,
        "total": 1
      },
      {
        "name": "Annotations",
        "ahead": true,
        "covered": 0,
        "total": 1
      }
    ],
    "byConcept": {
      "overloading": 223,
      "inheritance": 207,
      "strings": 178,
      "string-pool": 177,
      "statements": 174,
      "casting": 170,
      "polymorphism": 170,
      "constructors": 159,
      "static": 152,
      "encapsulation": 142,
      "classes": 128,
      "operators": 118,
      "break-continue": 117,
      "object-class": 116,
      "abstract": 103,
      "records-enums": 103,
      "wrappers": 96,
      "loops": 74,
      "if-else": 60,
      "literals": 57,
      "switch": 43,
      "checked-unchecked": 27,
      "multi-catch": 27,
      "primitives": 22,
      "var": 22,
      "text-blocks": 21,
      "arrays": 21,
      "exceptions": 3,
      "throw-throws": 1
    }
  }
};
