// Auto-generated by scripts/suggest.js. Do NOT edit — run 'npm run revise'.
const SUGGESTIONS = {
  "generated": "2026-09-23T14:37:07.611Z",
  "items": [
    {
      "key": "Chapter 13: OOP Concepts|src/Chapter_13_OOPSConcepts/Sub_Chapter_4_Constructors/Sub_Chapter_2_This_And_Super/SuperKeywordUseExample.java|construct|inheritance",
      "kind": "construct",
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Super Keyword Use Example",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_4_Constructors/Sub_Chapter_2_This_And_Super/SuperKeywordUseExample.java",
      "what": "inheritance",
      "why": "the code uses inheritance, and the notes never explain it",
      "draft": [
        "inheritance :- the code in this topic uses this, but the notes do not explain it.",
        "Note :- a reader who has not met inheritance yet cannot follow the example."
      ]
    },
    {
      "key": "Chapter 13: OOP Concepts|src/Chapter_13_OOPSConcepts/Sub_Chapter_8_Plain_Old_Java_Objects/POJOExample/Main.java|construct|a static member",
      "kind": "construct",
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Main",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_8_Plain_Old_Java_Objects/POJOExample/Main.java",
      "what": "a static member",
      "why": "the code uses a static member, and the notes never explain it",
      "draft": [
        "a static member :- the code in this topic uses this, but the notes do not explain it.",
        "Note :- a reader who has not met a static member yet cannot follow the example."
      ]
    },
    {
      "key": "Chapter 13: OOP Concepts|src/Chapter_13_OOPSConcepts/Sub_Chapter_11_Inheritance/AnimalInheritanceExample/Fish.java|construct|inheritance",
      "kind": "construct",
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Fish",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_11_Inheritance/AnimalInheritanceExample/Fish.java",
      "what": "inheritance",
      "why": "the code uses inheritance, and the notes never explain it",
      "draft": [
        "inheritance :- the code in this topic uses this, but the notes do not explain it.",
        "Note :- a reader who has not met inheritance yet cannot follow the example."
      ]
    },
    {
      "key": "Chapter 13: OOP Concepts|src/Chapter_13_OOPSConcepts/Sub_Chapter_11_Inheritance/AnimalInheritanceExample/Inheritance.java|construct|a static member",
      "kind": "construct",
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Inheritance",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_11_Inheritance/AnimalInheritanceExample/Inheritance.java",
      "what": "a static member",
      "why": "the code uses a static member, and the notes never explain it",
      "draft": [
        "a static member :- the code in this topic uses this, but the notes do not explain it.",
        "Note :- a reader who has not met a static member yet cannot follow the example."
      ]
    },
    {
      "key": "Chapter 13: OOP Concepts|src/Chapter_13_OOPSConcepts/Sub_Chapter_13_Method_OverLoading_In_Java/MethodOverloadingInJava.java|construct|a static member",
      "kind": "construct",
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Method Overloading In Java",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_13_Method_OverLoading_In_Java/MethodOverloadingInJava.java",
      "what": "a static member",
      "why": "the code uses a static member, and the notes never explain it",
      "draft": [
        "a static member :- the code in this topic uses this, but the notes do not explain it.",
        "Note :- a reader who has not met a static member yet cannot follow the example."
      ]
    },
    {
      "key": "Chapter 13: OOP Concepts|src/Chapter_13_OOPSConcepts/Sub_Chapter_14_Method_Overriding_In_Java/MethodOverridingExample/Dog.java|construct|inheritance",
      "kind": "construct",
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Dog",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_14_Method_Overriding_In_Java/MethodOverridingExample/Dog.java",
      "what": "inheritance",
      "why": "the code uses inheritance, and the notes never explain it",
      "draft": [
        "inheritance :- the code in this topic uses this, but the notes do not explain it.",
        "Note :- a reader who has not met inheritance yet cannot follow the example."
      ]
    },
    {
      "key": "Chapter 14: Strings|src/Chapter_14_Strings/Sub_Chapter_2_String_Methods_And_Best_Practices/StringMethodAndBestPractices.java|api|printf",
      "kind": "api",
      "chapter": "Chapter 14: Strings",
      "topic": "String Method And Best Practices",
      "file": "src/Chapter_14_Strings/Sub_Chapter_2_String_Methods_And_Best_Practices/StringMethodAndBestPractices.java",
      "what": "printf",
      "why": "the code calls printf, and the notes never mention printf",
      "draft": [
        "printf :- used in this topic's code but not explained in the notes.",
        "Note :- say what printf does, what it takes, and what it gives back, so the code above is not taken on trust."
      ]
    },
    {
      "key": "Chapter 14: Strings|src/Chapter_14_Strings/Sub_Chapter_2_String_Methods_And_Best_Practices/StringMethodAndBestPractices.java|construct|String formatting",
      "kind": "construct",
      "chapter": "Chapter 14: Strings",
      "topic": "String Method And Best Practices",
      "file": "src/Chapter_14_Strings/Sub_Chapter_2_String_Methods_And_Best_Practices/StringMethodAndBestPractices.java",
      "what": "String formatting",
      "why": "the code uses String formatting, and the notes never explain it",
      "draft": [
        "String formatting :- the code in this topic uses this, but the notes do not explain it.",
        "Note :- a reader who has not met String formatting yet cannot follow the example."
      ]
    }
  ]
};
