// Auto-generated by scripts/suggest.js. Do NOT edit — run 'npm run revise'.
const SUGGESTIONS = {
  "schemaVersion": 2,
  "sourceFingerprint": "d73d21b3b2815bdb78382d2f1e0c4710f4815317697635abd048b4c96e3a4ef2",
  "frameworkFingerprint": "bc2d8a65d0acbf835dfdd444220ecde8b76cbe44fed28f72c943e1a2c87030bc",
  "items": [
    {
      "key": "editorial|src/Chapter_13_OOPSConcepts/Sub_Chapter_2_Getters_Encapsulation_Object_Access/Car.java|derived-getter|751ec3d01a94",
      "kind": "editorial",
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Car",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_2_Getters_Encapsulation_Object_Access/Car.java",
      "line": 128,
      "what": "Name what a derived getter returns",
      "why": "\"Derived in some way\" does not say what is derived or from what. Naming the calculation makes the point usable.",
      "category": "clarification",
      "before": "There could be getter methods for fields that are not really declared on your class but that are derived in some way.",
      "after": "A getter can also return a value that is not a stored field at all. For example, a getTotal() method could return quantity * price, working the value out each time instead of storing it.",
      "sourceFingerprint": "ac13049e016e6335bae4c25410af90544c3665315f96dca40b978389fb7933c4",
      "contentVersion": "0e5fa1f44c3ec380e9f6b693be2bfa3b7c9fc665ee220fe3ddc15dd866c5a065",
      "evidence": "review-required",
      "draft": [
        "Name what a derived getter returns",
        "A getter can also return a value that is not a stored field at all. For example, a getTotal() method could return quantity * price, working the value out each time instead of storing it."
      ]
    },
    {
      "key": "editorial|src/Chapter_13_OOPSConcepts/Sub_Chapter_4_Constructors/Sub_Chapter_1_ConstructorConcept/ConstructorConcept.java|single-initialization|1bfcb958eb92",
      "kind": "editorial",
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Constructor Concept",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_4_Constructors/Sub_Chapter_1_ConstructorConcept/ConstructorConcept.java",
      "line": 69,
      "what": "Name the benefit of one initialization constructor",
      "why": "\"A good way of doing things\" names neither the practice nor the benefit. The sentence continues on the next line, so the replacement joins it grammatically.",
      "category": "clarification",
      "before": "That's a good way of doing things, and it often leads to good coding because it avoids",
      "after": "Keeping the initialization in one constructor is better because it avoids",
      "sourceFingerprint": "ed032be4742a6431fe9d081aef6e6d2d4e648238eb69727117784ae74efb2243",
      "contentVersion": "7bc0f9346a6fb36c34e66e247c7d1b8b7d92653faefbfc86bb403433172145a8",
      "evidence": "review-required",
      "draft": [
        "Name the benefit of one initialization constructor",
        "Keeping the initialization in one constructor is better because it avoids"
      ]
    },
    {
      "key": "editorial|src/Chapter_13_OOPSConcepts/Sub_Chapter_4_Constructors/Sub_Chapter_2_This_And_Super/SuperKeywordUseExample.java|stack-overflow|9ecf49516ae3",
      "kind": "editorial",
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Super Keyword Use Example",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_4_Constructors/Sub_Chapter_2_This_And_Super/SuperKeywordUseExample.java",
      "line": 28,
      "what": "Correct the result of unbounded recursion",
      "why": "\"Memory is fully used\" describes running out of heap, not the stack. Unbounded recursion exhausts the call stack and throws StackOverflowError.",
      "category": "accuracy",
      "before": "What that means is that the method would call itself forever, or until memory is fully used, crashing the program. That's why we need the super keyword - so that we can call a method with the same name from a parent class.",
      "after": "What that means is that the method would call itself forever, until the call stack runs out of space and Java throws StackOverflowError. That's why we need the super keyword - so that we can call a method with the same name from a parent class.",
      "sourceFingerprint": "622409d9acafdf0156c835a4039acd65829c9fd1693b0d662ec9e3de79eeaba3",
      "contentVersion": "9ca961e4e1807aab68cb696a0e3a2f889b4b36127e5d05cd5dde6265a111dcd7",
      "evidence": "review-required",
      "draft": [
        "Correct the result of unbounded recursion",
        "What that means is that the method would call itself forever, until the call stack runs out of space and Java throws StackOverflowError. That's why we need the super keyword - so that we can call a method with the same name from a parent class."
      ]
    },
    {
      "key": "editorial|src/Chapter_13_OOPSConcepts/Sub_Chapter_8_Plain_Old_Java_Objects/PlainOldJavaObject.java|javabean-conventions|b2fcb3b9f0de",
      "kind": "editorial",
      "chapter": "Chapter 13: OOP Concepts",
      "topic": "Plain Old Java Object",
      "file": "src/Chapter_13_OOPSConcepts/Sub_Chapter_8_Plain_Old_Java_Objects/PlainOldJavaObject.java",
      "line": 18,
      "what": "Name the JavaBean conventions",
      "why": "\"Some extra rules\" names nothing. Listing the conventions makes the distinction from a plain POJO usable.",
      "category": "clarification",
      "before": "ii)  A JavaBean is just a POJO with some extra rules applied to it.",
      "after": "ii)  A JavaBean is a POJO with extra conventions: private fields, a public no-argument constructor, and public getter and setter methods for its properties.",
      "sourceFingerprint": "0d80ca878f05f1163079e227331358abc39d80bc9fdd137172f388cb14d04cb4",
      "contentVersion": "1a73fccf8505d7766eacaa0c32dfe67c180ce7dbb3a159d7ecc339264a839640",
      "evidence": "review-required",
      "draft": [
        "Name the JavaBean conventions",
        "ii)  A JavaBean is a POJO with extra conventions: private fields, a public no-argument constructor, and public getter and setter methods for its properties."
      ]
    }
  ]
};
